#pragma once

enum ErrorCodes {
	APP_GENERIC_ERROR = -1,
	APP_SUCCESS = 0,
	APP_INVALID_ARGUMENT = 1,
	APP_OUT_OF_MEMORY = 2,
	APP_FILE_NOT_FOUND = 3,
	APP_PERMISSION_DENIED = 4,
	APP_TIMEOUT = 5,
	APP_UNKNOWN_ERROR = 6
};
